
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("e764d8ea-5270-41e6-a0fb-467870c729d1")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("dWarneTSDatabaseModel", "FK_HeaderTransaction_MsPayment", "MsPayment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(MsPayment), "HeaderTransaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(HeaderTransaction), True)>
<Assembly: EdmRelationshipAttribute("dWarneTSDatabaseModel", "FK_HeaderTransaction_MsUser", "MsUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(MsUser), "HeaderTransaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(HeaderTransaction), True)>
<Assembly: EdmRelationshipAttribute("dWarneTSDatabaseModel", "DetailTransaction", "HeaderTransaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(HeaderTransaction), "MsComputer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(MsComputer))>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class dWarneTSDatabaseEntities1
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new dWarneTSDatabaseEntities1 object using the connection string found in the 'dWarneTSDatabaseEntities1' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=dWarneTSDatabaseEntities1", "dWarneTSDatabaseEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new dWarneTSDatabaseEntities1 object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "dWarneTSDatabaseEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new dWarneTSDatabaseEntities1 object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "dWarneTSDatabaseEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property HeaderTransactions() As ObjectSet(Of HeaderTransaction)
        Get
            If (_HeaderTransactions Is Nothing) Then
                _HeaderTransactions = MyBase.CreateObjectSet(Of HeaderTransaction)("HeaderTransactions")
            End If
            Return _HeaderTransactions
        End Get
    End Property

    Private _HeaderTransactions As ObjectSet(Of HeaderTransaction)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MsComputers() As ObjectSet(Of MsComputer)
        Get
            If (_MsComputers Is Nothing) Then
                _MsComputers = MyBase.CreateObjectSet(Of MsComputer)("MsComputers")
            End If
            Return _MsComputers
        End Get
    End Property

    Private _MsComputers As ObjectSet(Of MsComputer)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MsPayments() As ObjectSet(Of MsPayment)
        Get
            If (_MsPayments Is Nothing) Then
                _MsPayments = MyBase.CreateObjectSet(Of MsPayment)("MsPayments")
            End If
            Return _MsPayments
        End Get
    End Property

    Private _MsPayments As ObjectSet(Of MsPayment)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MsUsers() As ObjectSet(Of MsUser)
        Get
            If (_MsUsers Is Nothing) Then
                _MsUsers = MyBase.CreateObjectSet(Of MsUser)("MsUsers")
            End If
            Return _MsUsers
        End Get
    End Property

    Private _MsUsers As ObjectSet(Of MsUser)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the HeaderTransactions EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToHeaderTransactions(ByVal headerTransaction As HeaderTransaction)
        MyBase.AddObject("HeaderTransactions", headerTransaction)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MsComputers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMsComputers(ByVal msComputer As MsComputer)
        MyBase.AddObject("MsComputers", msComputer)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MsPayments EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMsPayments(ByVal msPayment As MsPayment)
        MyBase.AddObject("MsPayments", msPayment)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MsUsers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMsUsers(ByVal msUser As MsUser)
        MyBase.AddObject("MsUsers", msUser)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dWarneTSDatabaseModel", Name:="HeaderTransaction")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class HeaderTransaction
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new HeaderTransaction object.
    ''' </summary>
    ''' <param name="transactionid">Initial value of the Transactionid property.</param>
    ''' <param name="userid">Initial value of the Userid property.</param>
    ''' <param name="paymentid">Initial value of the Paymentid property.</param>
    ''' <param name="bookingdate">Initial value of the Bookingdate property.</param>
    ''' <param name="transactiondate">Initial value of the Transactiondate property.</param>
    Public Shared Function CreateHeaderTransaction(transactionid As Global.System.String, userid As Global.System.String, paymentid As Global.System.String, bookingdate As Global.System.DateTime, transactiondate As Global.System.DateTime) As HeaderTransaction
        Dim headerTransaction as HeaderTransaction = New HeaderTransaction
        headerTransaction.Transactionid = transactionid
        headerTransaction.Userid = userid
        headerTransaction.Paymentid = paymentid
        headerTransaction.Bookingdate = bookingdate
        headerTransaction.Transactiondate = transactiondate
        Return headerTransaction
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Transactionid() As Global.System.String
        Get
            Return _Transactionid
        End Get
        Set
            If (_Transactionid <> Value) Then
                OnTransactionidChanging(value)
                ReportPropertyChanging("Transactionid")
                _Transactionid = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Transactionid")
                OnTransactionidChanged()
            End If
        End Set
    End Property

    Private _Transactionid As Global.System.String
    Private Partial Sub OnTransactionidChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTransactionidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Userid() As Global.System.String
        Get
            Return _Userid
        End Get
        Set
            OnUseridChanging(value)
            ReportPropertyChanging("Userid")
            _Userid = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Userid")
            OnUseridChanged()
        End Set
    End Property

    Private _Userid As Global.System.String
    Private Partial Sub OnUseridChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUseridChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Paymentid() As Global.System.String
        Get
            Return _Paymentid
        End Get
        Set
            OnPaymentidChanging(value)
            ReportPropertyChanging("Paymentid")
            _Paymentid = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Paymentid")
            OnPaymentidChanged()
        End Set
    End Property

    Private _Paymentid As Global.System.String
    Private Partial Sub OnPaymentidChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPaymentidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Bookingdate() As Global.System.DateTime
        Get
            Return _Bookingdate
        End Get
        Set
            OnBookingdateChanging(value)
            ReportPropertyChanging("Bookingdate")
            _Bookingdate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Bookingdate")
            OnBookingdateChanged()
        End Set
    End Property

    Private _Bookingdate As Global.System.DateTime
    Private Partial Sub OnBookingdateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnBookingdateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Transactiondate() As Global.System.DateTime
        Get
            Return _Transactiondate
        End Get
        Set
            OnTransactiondateChanging(value)
            ReportPropertyChanging("Transactiondate")
            _Transactiondate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Transactiondate")
            OnTransactiondateChanged()
        End Set
    End Property

    Private _Transactiondate As Global.System.DateTime
    Private Partial Sub OnTransactiondateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnTransactiondateChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dWarneTSDatabaseModel", "FK_HeaderTransaction_MsPayment", "MsPayment")>
    Public Property MsPayment() As MsPayment
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MsPayment)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsPayment", "MsPayment").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MsPayment)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsPayment", "MsPayment").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property MsPaymentReference() As EntityReference(Of MsPayment)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MsPayment)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsPayment", "MsPayment")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of MsPayment)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsPayment", "MsPayment", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dWarneTSDatabaseModel", "FK_HeaderTransaction_MsUser", "MsUser")>
    Public Property MsUser() As MsUser
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MsUser)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsUser", "MsUser").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MsUser)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsUser", "MsUser").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property MsUserReference() As EntityReference(Of MsUser)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MsUser)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsUser", "MsUser")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of MsUser)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsUser", "MsUser", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dWarneTSDatabaseModel", "DetailTransaction", "MsComputer")>
     Public Property MsComputers() As EntityCollection(Of MsComputer)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of MsComputer)("dWarneTSDatabaseModel.DetailTransaction", "MsComputer")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of MsComputer)("dWarneTSDatabaseModel.DetailTransaction", "MsComputer", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dWarneTSDatabaseModel", Name:="MsComputer")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MsComputer
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MsComputer object.
    ''' </summary>
    ''' <param name="computerid">Initial value of the Computerid property.</param>
    ''' <param name="rowCol">Initial value of the RowCol property.</param>
    ''' <param name="status">Initial value of the Status property.</param>
    ''' <param name="reason">Initial value of the Reason property.</param>
    Public Shared Function CreateMsComputer(computerid As Global.System.String, rowCol As Global.System.String, status As Global.System.String, reason As Global.System.String) As MsComputer
        Dim msComputer as MsComputer = New MsComputer
        msComputer.Computerid = computerid
        msComputer.RowCol = rowCol
        msComputer.Status = status
        msComputer.Reason = reason
        Return msComputer
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Computerid() As Global.System.String
        Get
            Return _Computerid
        End Get
        Set
            If (_Computerid <> Value) Then
                OnComputeridChanging(value)
                ReportPropertyChanging("Computerid")
                _Computerid = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Computerid")
                OnComputeridChanged()
            End If
        End Set
    End Property

    Private _Computerid As Global.System.String
    Private Partial Sub OnComputeridChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnComputeridChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RowCol() As Global.System.String
        Get
            Return _RowCol
        End Get
        Set
            OnRowColChanging(value)
            ReportPropertyChanging("RowCol")
            _RowCol = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("RowCol")
            OnRowColChanged()
        End Set
    End Property

    Private _RowCol As Global.System.String
    Private Partial Sub OnRowColChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRowColChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Status() As Global.System.String
        Get
            Return _Status
        End Get
        Set
            OnStatusChanging(value)
            ReportPropertyChanging("Status")
            _Status = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Status")
            OnStatusChanged()
        End Set
    End Property

    Private _Status As Global.System.String
    Private Partial Sub OnStatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Reason() As Global.System.String
        Get
            Return _Reason
        End Get
        Set
            OnReasonChanging(value)
            ReportPropertyChanging("Reason")
            _Reason = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Reason")
            OnReasonChanged()
        End Set
    End Property

    Private _Reason As Global.System.String
    Private Partial Sub OnReasonChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnReasonChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dWarneTSDatabaseModel", "DetailTransaction", "HeaderTransaction")>
     Public Property HeaderTransactions() As EntityCollection(Of HeaderTransaction)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of HeaderTransaction)("dWarneTSDatabaseModel.DetailTransaction", "HeaderTransaction")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of HeaderTransaction)("dWarneTSDatabaseModel.DetailTransaction", "HeaderTransaction", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dWarneTSDatabaseModel", Name:="MsPayment")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MsPayment
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MsPayment object.
    ''' </summary>
    ''' <param name="paymentid">Initial value of the Paymentid property.</param>
    ''' <param name="method">Initial value of the Method property.</param>
    ''' <param name="accountnumber">Initial value of the Accountnumber property.</param>
    Public Shared Function CreateMsPayment(paymentid As Global.System.String, method As Global.System.String, accountnumber As Global.System.String) As MsPayment
        Dim msPayment as MsPayment = New MsPayment
        msPayment.Paymentid = paymentid
        msPayment.Method = method
        msPayment.Accountnumber = accountnumber
        Return msPayment
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Paymentid() As Global.System.String
        Get
            Return _Paymentid
        End Get
        Set
            If (_Paymentid <> Value) Then
                OnPaymentidChanging(value)
                ReportPropertyChanging("Paymentid")
                _Paymentid = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Paymentid")
                OnPaymentidChanged()
            End If
        End Set
    End Property

    Private _Paymentid As Global.System.String
    Private Partial Sub OnPaymentidChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPaymentidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Method() As Global.System.String
        Get
            Return _Method
        End Get
        Set
            OnMethodChanging(value)
            ReportPropertyChanging("Method")
            _Method = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Method")
            OnMethodChanged()
        End Set
    End Property

    Private _Method As Global.System.String
    Private Partial Sub OnMethodChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMethodChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Accountnumber() As Global.System.String
        Get
            Return _Accountnumber
        End Get
        Set
            OnAccountnumberChanging(value)
            ReportPropertyChanging("Accountnumber")
            _Accountnumber = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Accountnumber")
            OnAccountnumberChanged()
        End Set
    End Property

    Private _Accountnumber As Global.System.String
    Private Partial Sub OnAccountnumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAccountnumberChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dWarneTSDatabaseModel", "FK_HeaderTransaction_MsPayment", "HeaderTransaction")>
     Public Property HeaderTransactions() As EntityCollection(Of HeaderTransaction)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of HeaderTransaction)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsPayment", "HeaderTransaction")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of HeaderTransaction)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsPayment", "HeaderTransaction", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dWarneTSDatabaseModel", Name:="MsUser")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MsUser
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MsUser object.
    ''' </summary>
    ''' <param name="userid">Initial value of the Userid property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="password">Initial value of the Password property.</param>
    ''' <param name="gender">Initial value of the Gender property.</param>
    ''' <param name="creditCardNumber">Initial value of the CreditCardNumber property.</param>
    ''' <param name="bankName">Initial value of the BankName property.</param>
    ''' <param name="bankAccNumber">Initial value of the BankAccNumber property.</param>
    ''' <param name="lastUpdate">Initial value of the LastUpdate property.</param>
    Public Shared Function CreateMsUser(userid As Global.System.String, name As Global.System.String, password As Global.System.String, gender As Global.System.String, creditCardNumber As Global.System.String, bankName As Global.System.String, bankAccNumber As Global.System.String, lastUpdate As Global.System.DateTime) As MsUser
        Dim msUser as MsUser = New MsUser
        msUser.Userid = userid
        msUser.Name = name
        msUser.Password = password
        msUser.Gender = gender
        msUser.CreditCardNumber = creditCardNumber
        msUser.BankName = bankName
        msUser.BankAccNumber = bankAccNumber
        msUser.LastUpdate = lastUpdate
        Return msUser
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Userid() As Global.System.String
        Get
            Return _Userid
        End Get
        Set
            If (_Userid <> Value) Then
                OnUseridChanging(value)
                ReportPropertyChanging("Userid")
                _Userid = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Userid")
                OnUseridChanged()
            End If
        End Set
    End Property

    Private _Userid As Global.System.String
    Private Partial Sub OnUseridChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUseridChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Password() As Global.System.String
        Get
            Return _Password
        End Get
        Set
            OnPasswordChanging(value)
            ReportPropertyChanging("Password")
            _Password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Password")
            OnPasswordChanged()
        End Set
    End Property

    Private _Password As Global.System.String
    Private Partial Sub OnPasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Gender() As Global.System.String
        Get
            Return _Gender
        End Get
        Set
            OnGenderChanging(value)
            ReportPropertyChanging("Gender")
            _Gender = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Gender")
            OnGenderChanged()
        End Set
    End Property

    Private _Gender As Global.System.String
    Private Partial Sub OnGenderChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGenderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CreditCardNumber() As Global.System.String
        Get
            Return _CreditCardNumber
        End Get
        Set
            OnCreditCardNumberChanging(value)
            ReportPropertyChanging("CreditCardNumber")
            _CreditCardNumber = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("CreditCardNumber")
            OnCreditCardNumberChanged()
        End Set
    End Property

    Private _CreditCardNumber As Global.System.String
    Private Partial Sub OnCreditCardNumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCreditCardNumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BankName() As Global.System.String
        Get
            Return _BankName
        End Get
        Set
            OnBankNameChanging(value)
            ReportPropertyChanging("BankName")
            _BankName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("BankName")
            OnBankNameChanged()
        End Set
    End Property

    Private _BankName As Global.System.String
    Private Partial Sub OnBankNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBankNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BankAccNumber() As Global.System.String
        Get
            Return _BankAccNumber
        End Get
        Set
            OnBankAccNumberChanging(value)
            ReportPropertyChanging("BankAccNumber")
            _BankAccNumber = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("BankAccNumber")
            OnBankAccNumberChanged()
        End Set
    End Property

    Private _BankAccNumber As Global.System.String
    Private Partial Sub OnBankAccNumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBankAccNumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LastUpdate() As Global.System.DateTime
        Get
            Return _LastUpdate
        End Get
        Set
            OnLastUpdateChanging(value)
            ReportPropertyChanging("LastUpdate")
            _LastUpdate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastUpdate")
            OnLastUpdateChanged()
        End Set
    End Property

    Private _LastUpdate As Global.System.DateTime
    Private Partial Sub OnLastUpdateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnLastUpdateChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dWarneTSDatabaseModel", "FK_HeaderTransaction_MsUser", "HeaderTransaction")>
     Public Property HeaderTransactions() As EntityCollection(Of HeaderTransaction)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of HeaderTransaction)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsUser", "HeaderTransaction")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of HeaderTransaction)("dWarneTSDatabaseModel.FK_HeaderTransaction_MsUser", "HeaderTransaction", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


